jubilee:
  api:
    base-url: "https://jubipay.jubileeinsurance.com"

    # Auth Endpoint
    signin-url: "/api/auth/signin"
    username: "foresighttlc@jubileekenya.com"
    password: "8K1lPqs26%j{/<yJ"

    #IDD
    # GET Requests
    active-schemes-url: "/da/scheme/all-active-schemes/KENYA"
    pending-payroll-url: "/da/idd/pending-payroll/KENYA"
    idd-exception-report-url: "/da/idd/exception-report/KENYA"
    idd-member-setup-url: "/da/idd/get-idd-member-setup/KENYA"
    batch-numbers-url: "/da/idd/batch-no/KENYA"
    idd-batch-pending-processing-url: "/da/commissions/batch-numbers-pending-payments/KENYA"
    scheme-companies-url: "/da/company/companies/KENYA"
    member-information-url: "/da/members/member-information/KENYA"
    user-email: "/da/users/by-email/KENYA"
    members-list: "/da/members/KENYA"
    bank-details: "/da/payments/bank-details/KENYA"

    # POST Requests (With Request Bodies)
    idd-withdrawal-approve-url: "/da/idd/approve-idd-withdrawal/KENYA"
    idd-withdrawal-reject-url: "/da/idd/reject-idd-withdrawal/KENYA"
    batch-approve-url: "/da/idd/approve-batch/KENYA"
    batch-reject-url: "/da/idd/reject-batch/KENYA"
    commissions-list-url: "/da/commissions/comm-payments-list/KENYA"
    commissions-reject-list-url: "/da/commissions/comm-payments/reject/KENYA"
    withdrawal-statement-url: "/da/statements/withdrawal-statement/KENYA"


    # COMMISSIONS
    # Get Requests
    commissions-by-receipt-url: "/da/commissions/KENYA"
    commissions-pending-batch-nos-url: "/da/commissions/pending-batch-nos/KENYA"
    batch-agent-listing-url: "/da/commissions/batch-agent-listing/KENYA"
    commissions-approval-list-url: "/da/commissions/approval-list/KENYA"
    commissions-reversal-list-url: "/da/commissions/reversal/KENYA"
    commissions-batch-pending-payments-url: "/da/commissions/batch-numbers-pending-payments/KENYA"
    commissions-receipts-per-batch-url: "/da/commissions/rpt/receipts-per-batch/KENYA"
    commissions-vouchers-per-batch-url: "/da/commissions/rpt/vouchers-per-batch/KENYA"
    commissions-exception-report-url: "/da/commissions/exception-report/KENYA"
    intermediaries-all-url: "/da/intermediary/all/KENYA"

    # Post Requests (With Request Bodies)
    commissions-process-url: "/da/commissions/process/KENYA"
    commissions-approve-url: "/da/commissions/approve/KENYA"
    commissions-reverse-url: "/da/commissions/reverse/KENYA"
    commissions-reject-url: "/da/commissions/reject/KENYA"
    commissions-payments-pending-approval-url: "/da/commissions/comm-payments-list/KENYA"
    commissions-payments-reject-reverse-url: "/da/commissions/comm-payments/reject/KENYA"


# --- UPLOAD TO OMNIDOCS ---
omnidocs:
  base-url: "http://localhost:9996"
  upload-endpoint: "api/v1/upload/"
  auth:
    username: "admin"
    password: "secure_password"
  max:
    concurrent-uploads: 3
    retries: 3
  connection-timeout: 60000
  read-timeout: 60000

spring:
  datasource:
    url: jdbc:oracle:thin:@//jubilee-life-workflow-proddb1.c9sqi8igyeah.eu-west-1.rds.amazonaws.com:1521/wfprod
    username: jubileewflow
    password: '%$newJhlapex15@$$'
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logging
logging:
  level:
    root: INFO
    com.jubilee.config.jubileeservice: DEBUG
    org.springframework.web.reactive.function.client.WebClient: WARN